### PR TITLE
modified version with rrdtool

### PR DESCRIPTION
**Pull request by fbilly**
with a example rrd graph lastday.png

### CODE REVIEW

**Comment by Flameeyes** [comment]
Sorry for the extreme delay on this. Would you mind splitting this into separate commits for different features? Some of it appears to be improving the commenting of the code (good), but I would rather merge those separately.

Also for RRDTool output, I would like to have a separate Python file implementing the functionality, not only to keep the `main` module clean, but also because that way if the dependency is not around it'll just fail importing that module and the rest of the script will still work.

**Comment by fbilly** [comment]
Hi Diego,

no problem. can you help me to Split the code ?
I will use the rrd code in a separate python file, but i do not know how to include this new file in your primary python file.

Best Regards,
Florian

--------------

Am 03.09.17 um 18:26 schrieb Diego Elio Pettenò

**Comment by Flameeyes** [comment]
See the way I do it for the common code:

```python
from glucometerutils import rrdexport
```

and then have the rrd code in a file called `glucometerutils/rrdexport.py`

Just remember to add the header, including your copyright statement.

**Comment by fbilly** [comment]
Thanks for the Info, i test it in this way.

Best Regards,
Florian

-------- Original-Nachricht --------

Diego Elio Pettenò schrieb am 10.09.2017 um 12:12:

**Pull request closed without merging**
